Update 0-transfer_file

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -1,6 +1,9 @@
 #!/usr/bin/env bash
 # Script that transfers a file from client to server using scp
 
+# Exit immediately if a command exits with a non-zero status
+set -e
+
 # Check if less than 4 parameters are passed
 if [ "$#" -lt 4 ]; then
     echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
