Implement 0-transfer_file: File transfer script using SCP with SSH key

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -15,3 +15,10 @@ PATH_TO_SSH_KEY="$4"
 
 # Transfer file using scp with strict host key checking disabled
 scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
+
+# Checking if transfer was successful
+if [ $? -eq 0 ]; then
+	echo "FILE WAS TRANSFERED SUCCESSFULLY"
+else 
+	echo "FILE TRANSFER FAILED"
+fi
